CREATE TABLE MFCLIENT(
IDCLIENT INT IDENTITY(1,1) NOT NULL,
NAMECLIENT [varchar](50) NOT NULL,
TELEPHONE [varchar](30) NULL,
EMAIL [varchar](100) NULL,
ADDRESSCLIENT [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDCLIENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE MFPRODUCT(
IDPRODUCT INT IDENTITY(1,1) NOT NULL,
NAMEPRODUCT [varchar](50) NOT NULL,
DESCRIPTIONPRODUCT [varchar](100) NULL,
PRICE [float] DEFAULT (0),
PRIMARY KEY CLUSTERED 
(
	[IDPRODUCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE MFORDERS(
IDORDER INT IDENTITY(1,1) NOT NULL,
IDCLIENT [int] NOT NULL,
DTORDER [datetime] NULL,
TOTALPRICE [float] DEFAULT (0)
PRIMARY KEY CLUSTERED 
(
	[IDORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MFORDERS]  WITH CHECK ADD FOREIGN KEY([IDCLIENT])
REFERENCES [dbo].[MFCLIENT] ([IDCLIENT])
GO

CREATE TABLE MFORDERS_ITEMS(
IDORDER_ITEM INT IDENTITY(1,1) NOT NULL,
IDORDER [int] NOT NULL,
IDPRODUCT [int] NOT NULL,
AMOUNT [int] NOT NULL,
PRICE [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDORDER_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MFORDERS_ITEMS]  WITH CHECK ADD FOREIGN KEY([IDORDER])
REFERENCES [dbo].[MFORDERS] ([IDORDER])
GO

ALTER TABLE [dbo].[MFORDERS_ITEMS]  WITH CHECK ADD FOREIGN KEY([IDPRODUCT])
REFERENCES [dbo].[MFPRODUCT] ([IDPRODUCT])
GO